import logging
import sys
import sqlite3


def main():
    # set up for logging
    LEVELS = {'debug': logging.DEBUG,
              'info': logging.INFO,
              'warning': logging.WARNING,
              'error': logging.ERROR,
              'critical': logging.CRITICAL,
              }
    if len(sys.argv) > 1:
        level_name = sys.argv[1]
        level = LEVELS.get(level_name, logging.NOTSET)
        logging.basicConfig(level=level)

    logger = logging.getLogger()
    logger.debug('Entering Main')

    db = sqlite3.connect('../well.sqlite')
    cur = db.cursor()

    logger.debug('calling create_readings_table')
    create_reading_date_table(cur)

    # save, then close the cursor and db
    db.commit()
    cur.close()
    db.close()


def create_reading_date_table(c):
    c.execute('DROP TABLE IF EXISTS reading_date')
    c.execute('CREATE TABLE IF NOT EXISTS \
                reading_date(reading_id INTEGER PRIMARY KEY, date TEXT)')

    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2000-05-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2000-06-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2000-07-31", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2000-08-28", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2000-09-27", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2000-10-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2000-11-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2000-12-27", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-01-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-02-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-03-27", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-04-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-05-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-06-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-07-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-08-27", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-09-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-10-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-11-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2001-12-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-01-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-02-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-03-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-04-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-05-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-06-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-07-28", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-08-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-09-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-10-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-11-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-12-25", ))
    # c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2002-12-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-01-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-02-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-03-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-04-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-05-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-06-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-07-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-08-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-09-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-10-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-11-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2003-12-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-01-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-02-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-03-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-04-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-05-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-06-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-07-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-08-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-09-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-10-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-11-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2004-12-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-01-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-03-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-04-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-05-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-06-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-07-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-08-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-09-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-10-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-11-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2005-12-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-01-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-02-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-03-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-04-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-05-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-06-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-07-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-08-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-09-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-10-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-11-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2006-12-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-01-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-02-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-03-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-04-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-05-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-06-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-07-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-08-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-09-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-10-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-11-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2007-12-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-01-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-02-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-03-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-04-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-05-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-06-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-07-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-08-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-09-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-10-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-11-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2008-12-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-01-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-02-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-03-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-04-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-05-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-06-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-07-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-08-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-09-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-10-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-11-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2009-12-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-01-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-02-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-03-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-04-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-05-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-06-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-07-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-08-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-09-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-10-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-11-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2010-12-27", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-01-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-02-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-03-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-04-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-05-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-06-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-07-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-08-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-09-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-10-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-11-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2011-12-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-01-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-02-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-03-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-04-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-05-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-06-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-07-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-08-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-09-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-10-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-11-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2012-12-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-01-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-02-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-03-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-04-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-05-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-06-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-07-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-08-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-09-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-10-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-11-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2013-12-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-01-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-02-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-03-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-04-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-05-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-06-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-07-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-08-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-09-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-10-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-11-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2014-12-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-01-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-02-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-03-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-04-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-05-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-06-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-07-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-08-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-09-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-10-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-11-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2015-12-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-01-14", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-02-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-03-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-04-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-05-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-06-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-07-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-08-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-09-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-10-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-11-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2016-12-16", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-01-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-02-17", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-03-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-04-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-05-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-06-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-07-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-08-20", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-09-19", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-10-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-11-28", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2017-12-21", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-01-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-02-18", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-03-22", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-05-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-06-23", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-07-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-08-25", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-09-28", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-10-30", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-11-26", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2018-12-27", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2019-01-24", ))
    c.execute("INSERT INTO reading_date (date) VALUES (?)", ("2019-02-27", ))


if __name__ == '__main__':
    main()



