import logging
import sys
import sqlite3


def main():
    # set up for logging
    LEVELS = {'debug': logging.DEBUG,
              'info': logging.INFO,
              'warning': logging.WARNING,
              'error': logging.ERROR,
              'critical': logging.CRITICAL,
              }
    if len(sys.argv) > 1:
        level_name = sys.argv[1]
        level = LEVELS.get(level_name, logging.NOTSET)
        logging.basicConfig(level=level)

    logger = logging.getLogger()
    logger.debug('Entering Main')

    db = sqlite3.connect('../well.db')
    cur = db.cursor()

    logger.debug('calling create_readings_table')
    create_readings_table(cur)

    # save, then close the cursor and db
    db.commit()
    cur.close()
    db.close()


def create_readings_table(c):
    c.execute('DROP TABLE IF EXISTS reading_dates')
    c.execute('CREATE TABLE IF NOT EXISTS \
                reading_dates(reading_date_id INTEGER PRIMARY KEY, reading_date TEXT)')

    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2000-25-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2000-26-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2000-31-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2000-28-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2000-27-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2000-25-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2000-21-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2000-27-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-24-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-26-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-27-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-24-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-24-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-26-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-26-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-27-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-26-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-26-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-26-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2001-26-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-26-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-24-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-28-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2002-25-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-26-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-25-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2003-24-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-22-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-23-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-24-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-22-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-25-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-24-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-24-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-26-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-23-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-22-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-22-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2004-23-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-21-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-25-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-21-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-23-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-23-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-22-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-24-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-22-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-22-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-21-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2005-23-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-23-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-22-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-24-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-24-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-23-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-23-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-22-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-22-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-22-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-21-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-20-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2006-21-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-23-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-23-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-24-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-22-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-22-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-22-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-23-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-22-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-21-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-20-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-20-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2007-20-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-21-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-21-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-21-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-19-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-20-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-21-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-20-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-18-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-18-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-18-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-17-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2008-20-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-24-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-21-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-20-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-21-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-20-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-21-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-23-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-18-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-18-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-17-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-22-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2009-22-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-21-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-20-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-23-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-23-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-21-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-22-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-26-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-25-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-25-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-24-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-20-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2010-27-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-25-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-24-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-26-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-26-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-19-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-23-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-23-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-21-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-22-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-21-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-19-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2011-20-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-20-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-19-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-23-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-20-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-19-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-20-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-19-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-18-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-19-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-19-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-18-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2012-18-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-17-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-19-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-22-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-20-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-20-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-21-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-20-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-18-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-17-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-19-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-19-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2013-20-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-19-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-18-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-22-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-21-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-25-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-21-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-19-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-22-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-20-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-17-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-19-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2014-19-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-19-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-20-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-21-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-23-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-21-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-21-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-20-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-19-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-19-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-17-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-18-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2015-19-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-14-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-20-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-17-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-21-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-18-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-17-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-21-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-19-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-20-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-20-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-19-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2016-16-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-23-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-17-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-25-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-25-04", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-22-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-21-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-18-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-20-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-19-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-23-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-28-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2017-21-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-24-01", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-18-02", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-22-03", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-25-05", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-23-06", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-25-07", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-25-08", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-28-09", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-30-10", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-26-11", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2018-27-12", ))
    c.execute("INSERT INTO reading_dates (reading_date) VALUES (?)", ("2019-24-01", ))


if __name__ == '__main__':
    main()



